### ISSUE TITLE
Add related assets (notebooks) to CodeNet dataset

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/katalog#25]
In order to run the 2 notebooks associated with the CodeNet dataset, the dataset YAML needs to include a `related_assets` like this:

```YAML
    related_assets:
      - name: MLX Language classification notebook
        description: Language classification notebook with CodeNet dataset mounted as PVC
        mime_type: application/x-ipynb+json
        application:
          name: MLX
          asset_id: notebooks/project-codenet-language-classification
```
