### ISSUE TITLE
Remove "MAX" prefix from model names

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/katalog#47]
- [x]  katalog README (#46)
- [ ] model YAMLs, `name` 
   ```YAML
   name: MAX Image Caption Generator
   model_identifier: max-image-caption-generator
   description: "IBM Model Asset eXchange(MAX) model that generates captions from a fixed vocabulary describing the contents of images in the COCO dataset"
   ```
- [ ] `mlx` bootstrapper and quickstart `catalog_upload.json`
- [ ] list of models in [model-samples/README.md](https://github.com/machine-learning-exchange/katalog/tree/main/model-samples#list-of-sample-models)
- [ ] rename YAML and MD file names (optional)

FYI @animeshsingh
